### ISSUE TITLE
Bacheca prenotazioni non va

### ISSUE THREAD

**Issue by Sladerix** [dariowskii/esse3_unimore#1]
Ciao, ho scaricato ieri l’app per iOS, purtroppo ho notato che la “bacheca prenotazioni” nel menu a scomparsa da sinistra non va. 
se ci clicco esce per un attimo il caricamento e poi scompare lasciando la pagina bianca.
(Ho una prenotazione)

In ogni caso bellissima app !!

**Comment by dariowskii** [comment]
Ciao Sladerix, si sono a conoscenza di questo errore che di fatto è stato segnalato da molti studenti. Purtroppo è un problema del sito di esse3, che come saprai è stato molto probabilmente sviluppato da una scimmia battendo su tasti a caso...
Scherzi a parte, sto cercando di risolvere questo ed altri problemi e per questo sto ritardando nel rilasciare l'aggiornamento, ma almeno sarà ricco!

Grazie mille comunque e soprattutto per riportato il problema, siete tutti/e fondamentali per lo sviluppo!

**Comment by Sladerix** [comment]
Ottimo! Continua così!



Volevo chiederti una cosa, tu per aver sviluppato quest’app hai ricevuto qualche riconoscimento dall’Università?

Antonello Barbone
Il 3 feb 2021, 17:45 +0100, Dario Varriale <notifications@github.com>, ha scritto:

**Comment by dariowskii** [comment]
Ni, ti spiego tutto per messaggio privato. Contattami pure a dariovarrialeapps@gmail.com !
Grazie mille comunque!!!
