### ISSUE TITLE
Escape caratteri riservati nei campi username e password

### ISSUE THREAD

**Issue by qpits** [dariowskii/esse3_unimore#3]
Ciao @dariowskii, apro questo issue riguardo un problema riscontrato durante il login.

Se la password o l’user inseriti contengono caratteri riservati nella composizione dell’URL (ad esempio “&” o “%”), non risulta possibile fare il login e l’applicativo risponde con un dialog “credenziali errate”.

Ho provato a fare l’escape dei caratteri direttamente nel campo di inserimento: il login è avvenuto con successo. Suppongo che occorra eseguire una sostituzione di questi caratteri con i rispettivi escape (ad esempio, sostituire “%” con “%25”).

**Comment by dariowskii** [comment]
Mitic*! Non avevo minimamente pensato a fare un escape poichè davo per scontato che la facessero loro lato server 🙃 Ovviamente mi ero scordato di chi stiamo parlando ahahah, se vuoi fare una pull request mi aiuteresti un tot! Altrimenti contattami su telegram (stesso nick) e ci organizziamo ✌🏽
