### ISSUE TITLE
Scroll bacheca prenotazioni blocca visualizzazione elementi

### ISSUE THREAD

**Issue by qpits** [dariowskii/esse3_unimore#4]
Quando è presente più di un elemento (prenotazione esame) ed è necessario uno scroll verso l’alto (per vedere gli elementi al di sotto del primo), questo viene eseguito parzialmente (non arriva fino al fondo dell’ultimo elemento).

Risultato: quando ho due elementi è possibile raggiungere i pulsanti solo del primo, mentre quelli del secondo sono “nascosti” sotto il limite inferiore dello schermo, anche dopo lo scroll.

**Comment by dariowskii** [comment]
Finalmente risolta (dopo troppo, lo so) nella nuova versione!
