### ISSUE TITLE
Uso delle API REST

### ISSUE THREAD

**Issue by WAPEETY** [dariowskii/esse3_unimore#7]
So che sembra una pazzia e non so se é uno sbaglio il fatto che esista la pagina ma ogni installazione di esse3 fornisce una documentazione dettagliata delle sue API, potete consultarle a: https://www.esse3.unimore.it/e3rest/docs/

**Comment by dariowskii** [comment]
Ciao @WAPEETY! 👋🏼

Ti ringrazio intanto per l'interesse!

Purtroppo anche io tempo fa mi sono imbattuto in questo swagger pensando che ci fossero a disposizione delle API pubbliche. Una volta provate a utilizzare ho scoperto (successivamente mi è stato confermato da chi tiene dietro la struttura) che sono accessibili solo tramite indirizzi IP abilitati 🥲

Onestamente il fatto che parte della documentazione API sia pubblica è alquanto un mistero, ma di fatto è incompleta e potrebbe essere benissimo un refuso lasciato li da moooolto tempo 😅

Ahimè, chiamando da postman mi sputa ancora fuori lo stesso messaggio di anni fa, quindi credo non sia cambiato nulla.

`GET https://www.esse3.unimore.it/e3rest/api/login`

```json
{
   "errDetails":[
      
   ],
   "retCode":-9999,
   "retErrMsg":"L'ip non \u00E8 tra quelli abilitati all'accesso alla risorsa richiesta",
   "statusCode":403
}
```

**Comment by WAPEETY** [comment]
Perdonami, io sono dell'Universitá di Venezia e non c'é questa restrizione, credo che sia un blocco messo con un WAF da UniMoRe.
Dovreste parlare con qualcuno in universitá ma non so se vi daranno l'opportunitá o scoperta l'app provino a bloccare anche lo scraping

Anche perché quella risposta non c'é nello swagger

**Comment by WAPEETY** [comment]
Una seconda idea potrebbe essere fare le richieste tramite quella pagina di swagger e fare scraping su quella

**Comment by dariowskii** [comment]
Purtroppo ho utilizzato lo scraping fin dall'inizio, ma il mantenimento dell'applicazione è diventato sempre più insidioso e terribile. Ho provato per circa 2 anni ad avviare un dialogo con UniMoRe ma essendo una persona singola, non un'azienda, "non mi avrebbero mai dato l'accesso alle API" (parole loro) nonostante abbia anche proposto la concessione dell'applicazione all'università gratuitamente e offerto anche il mantenimento.

Ahimè ci ho provato, ho continuato, ma a una certa è diventata ingestibile e se neanche l'università vuole darmi una mano in merito io non posso fare altro che dismetterla (che purtroppo è quello che è successo).

Da quel che so effettivamente è una delle poche università che non mette a disposizione le API di esse3, yuppii 🫠

Grazie ancora per l'interesse comunque!
